import { chromium } from "/Users/danielmatias/.npm/_npx/7d835fc058142333/node_modules/playwright/index.mjs";
import fs from "node:fs";
const env = Object.fromEntries(fs.readFileSync(".env.local","utf8").split("\n").filter(l=>l.includes("=")&&!l.trim().startsWith("#")).map(l=>{const i=l.indexOf("=");return [l.slice(0,i).trim(), l.slice(i+1).trim().replace(/^"|"$/g,"")]}));
const b = await chromium.launch({ executablePath: "/Users/danielmatias/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell" });
const p = await (await b.newContext({ viewport: { width: 1280, height: 1000 } })).newPage();
await p.goto("http://localhost:3000/login", { waitUntil: "networkidle" });
await p.fill('input[type="email"]', env.APP_LOGIN_EMAIL);
await p.fill('input[type="password"]', env.APP_LOGIN_PASSWORD);
await p.click('button[type="submit"]');
await p.waitForSelector("aside", { timeout: 25000 });
await p.goto("http://localhost:3000/dashboard/settings", { waitUntil: "networkidle" });
await p.waitForTimeout(1200);
const sw = p.locator('[role="switch"]').first();
await sw.scrollIntoViewIfNeeded();
const track = await sw.boundingBox();
const knob = await sw.locator("span").first().boundingBox();
console.log("track:", JSON.stringify({x:Math.round(track.x),w:Math.round(track.width),h:Math.round(track.height)}));
console.log("knob :", JSON.stringify({x:Math.round(knob.x),w:Math.round(knob.width),h:Math.round(knob.height)}));
const overhang = Math.round((knob.x + knob.width) - (track.x + track.width));
console.log("knob right edge vs track right edge:", overhang, "px", overhang > 0 ? "  <-- KNOB ESCAPES THE TRACK" : "  (inside)");
await sw.screenshot({ path: "/tmp/toggle.png" });
await b.close();
