import type {
  Industry,
  CompanyStatus,
  Confidence,
  PageType,
  FindStatus,
  VerificationStatus,
} from "./supabase/types";

export interface Evidence {
  quote: string;
  sourceUrl: string;
  pageType: PageType;
  disproveNotes?: string;
}

export interface Contact {
  name: string | null;
  nameInferred: boolean;
  title: string | null;
  email: string | null;
  findStatus: FindStatus;
  verificationStatus: VerificationStatus;
}

export interface Company {
  id: string;
  domain: string;
  name: string;
  industry: Industry;
  state: string;
  city: string;
  revenueBand: string;
  employeeBand: string;
  status: CompanyStatus;
  confidence: Confidence | null;
  rejectionReason: string | null;
  founderName: string | null;
  founderTitle: string | null;
  nextGenName: string | null;
  nextGenTitle: string | null;
  sourceUrl: string | null;
  firstSeenAt: string;
  lastCrawledAt: string;
  evidence: Evidence | null;
  contact: Contact | null;
}

// The pipeline is live now (lib/pipeline/*.ts, lib/searches-store.tsx) — the
// app no longer imports MOCK_COMPANIES. Kept only as a fixture for local UI
// work without spending real Apify/OpenRouter/Anymailfinder/MillionVerifier
// credits; the `Company`/`Evidence`/`Contact` types above are still the real,
// actively-used shape the live data gets mapped into. Fictional companies,
// target ICP per
// Scope_Jonathan_Goldhill_Engine.md: family-owned landscaping + home-building
// companies, $3-15M revenue, four agreed states (placeholder states below).
export const MOCK_COMPANIES: Company[] = [
  {
    id: "co-001",
    domain: "whittakerlandscape.example.com",
    name: "Whittaker Lawn & Landscape",
    industry: "landscaping",
    state: "TX",
    city: "Round Rock",
    revenueBand: "$6M–$9M",
    employeeBand: "35-50",
    status: "qualified",
    confidence: "high",
    rejectionReason: null,
    founderName: "Gary Whittaker",
    founderTitle: "Founder & President",
    nextGenName: "Casey Whittaker",
    nextGenTitle: "Operations Manager",
    sourceUrl: "https://whittakerlandscape.example.com/about",
    firstSeenAt: "2026-08-01",
    lastCrawledAt: "2026-08-04",
    evidence: {
      quote:
        "\"Gary founded the company in 1994, and today his daughter Casey runs day-to-day operations as we plan for the next chapter of Whittaker.\"",
      sourceUrl: "https://whittakerlandscape.example.com/about",
      pageType: "about",
      disproveNotes:
        "Re-checked live site: language unchanged on re-fetch, both names still co-listed with distinct titles. Holds as High.",
    },
    contact: {
      name: "Casey Whittaker",
      nameInferred: false,
      title: "Operations Manager",
      email: "casey@whittakerlandscape.example.com",
      findStatus: "found",
      verificationStatus: "valid",
    },
  },
  {
    id: "co-002",
    domain: "ashfordcustomhomes.example.com",
    name: "Ashford Custom Homes",
    industry: "home_builder",
    state: "NC",
    city: "Cary",
    revenueBand: "$9M–$14M",
    employeeBand: "40-60",
    status: "qualified",
    confidence: "high",
    rejectionReason: null,
    founderName: "Robert Ashford",
    founderTitle: "Founder",
    nextGenName: "Will Ashford",
    nextGenTitle: "VP of Construction",
    sourceUrl: "https://ashfordcustomhomes.example.com/our-team",
    firstSeenAt: "2026-07-30",
    lastCrawledAt: "2026-08-04",
    evidence: {
      quote:
        "\"After 28 years building homes across the Triangle, Robert is proud to have his son Will leading construction operations as the second generation of Ashford.\"",
      sourceUrl: "https://ashfordcustomhomes.example.com/our-team",
      pageType: "team",
      disproveNotes: "Confirmed against cached + live version — consistent. Holds as High.",
    },
    contact: {
      name: "Will Ashford",
      nameInferred: false,
      title: "VP of Construction",
      email: "will@ashfordcustomhomes.example.com",
      findStatus: "found",
      verificationStatus: "valid",
    },
  },
  {
    id: "co-003",
    domain: "cornerstonefamilyhomes.example.com",
    name: "Cornerstone Family Homes",
    industry: "home_builder",
    state: "OH",
    city: "Dublin",
    revenueBand: "$5M–$8M",
    employeeBand: "25-40",
    status: "qualified",
    confidence: "medium",
    rejectionReason: null,
    founderName: "Denise Corbin",
    founderTitle: "President",
    nextGenName: "Marcus Corbin",
    nextGenTitle: "Project Manager",
    sourceUrl: "https://cornerstonefamilyhomes.example.com/about-us",
    firstSeenAt: "2026-07-28",
    lastCrawledAt: "2026-08-03",
    evidence: {
      quote:
        "\"Our team includes Denise Corbin, who's led the company since 1998, and Marcus Corbin, who grew up on job sites and now manages projects across central Ohio.\"",
      sourceUrl: "https://cornerstonefamilyhomes.example.com/about-us",
      pageType: "about",
      disproveNotes:
        "No explicit succession/transition phrase — family relationship and generational framing implied, not stated. Downgraded from High to Medium on the disprove pass.",
    },
    contact: {
      name: "Marcus Corbin",
      nameInferred: false,
      title: "Project Manager",
      email: null,
      findStatus: "not_found",
      verificationStatus: "not_attempted",
    },
  },
  {
    id: "co-004",
    domain: "reyesgrounds.example.com",
    name: "Reyes Grounds Management",
    industry: "landscaping",
    state: "GA",
    city: "Alpharetta",
    revenueBand: "$4M–$6M",
    employeeBand: "20-35",
    status: "qualified",
    confidence: "medium",
    rejectionReason: null,
    founderName: "Hector Reyes",
    founderTitle: "Owner",
    nextGenName: "Sofia Reyes",
    nextGenTitle: "Account Manager",
    sourceUrl: "https://reyesgrounds.example.com/about",
    firstSeenAt: "2026-07-27",
    lastCrawledAt: "2026-08-02",
    evidence: {
      quote:
        "\"Started by Hector Reyes in 2001. His daughter Sofia now manages our largest commercial accounts and is learning the business from the ground up.\"",
      sourceUrl: "https://reyesgrounds.example.com/about",
      pageType: "about",
      disproveNotes: "\"Learning the business\" reads as in-progress transition, not confirmed handoff — Medium holds.",
    },
    contact: {
      name: "Sofia Reyes",
      nameInferred: false,
      title: "Account Manager",
      email: "sofia@reyesgrounds.example.com",
      findStatus: "found",
      verificationStatus: "risky",
    },
  },
  {
    id: "co-005",
    domain: "thackerayhomes.example.com",
    name: "Thackeray Home Builders",
    industry: "home_builder",
    state: "TX",
    city: "Georgetown",
    revenueBand: "$10M–$15M",
    employeeBand: "45-65",
    status: "qualified",
    confidence: "high",
    rejectionReason: null,
    founderName: "Paul Thackeray",
    founderTitle: "Founder & CEO",
    nextGenName: "Emma Thackeray-Voss",
    nextGenTitle: "Director of Operations",
    sourceUrl: "https://thackerayhomes.example.com/leadership",
    firstSeenAt: "2026-07-25",
    lastCrawledAt: "2026-08-04",
    evidence: {
      quote:
        "\"Paul Thackeray founded the company in 1989. In 2024, his daughter Emma Thackeray-Voss stepped into the Director of Operations role as part of our ongoing leadership transition.\"",
      sourceUrl: "https://thackerayhomes.example.com/leadership",
      pageType: "leadership",
      disproveNotes: "Explicit \"leadership transition\" language, dated. Clean High.",
    },
    contact: {
      name: "Emma Thackeray-Voss",
      nameInferred: false,
      title: "Director of Operations",
      email: "emma@thackerayhomes.example.com",
      findStatus: "found",
      verificationStatus: "valid",
    },
  },
  {
    id: "co-006",
    domain: "duttonlandscapedesign.example.com",
    name: "Dutton Landscape Design",
    industry: "landscaping",
    state: "NC",
    city: "Chapel Hill",
    revenueBand: "$3M–$5M",
    employeeBand: "15-25",
    status: "qualified",
    confidence: "verify",
    rejectionReason: null,
    founderName: "Frank Dutton",
    founderTitle: "Owner",
    nextGenName: "Jamie Dutton",
    nextGenTitle: null,
    sourceUrl: "https://duttonlandscapedesign.example.com/team",
    firstSeenAt: "2026-08-02",
    lastCrawledAt: "2026-08-04",
    evidence: {
      quote:
        "\"Frank started the company from a single truck in 1985. His kid Jamie has been around the business for years and is starting to take on more.\"",
      sourceUrl: "https://duttonlandscapedesign.example.com/team",
      pageType: "team",
      disproveNotes:
        "No title given for Jamie, relationship stated but role/scope vague (\"taking on more\" is not a defined leadership position). Flagged for a human look rather than scored High or Medium outright.",
    },
    contact: {
      name: "Jamie Dutton",
      nameInferred: false,
      title: null,
      email: null,
      findStatus: "not_found",
      verificationStatus: "not_attempted",
    },
  },
  {
    id: "co-007",
    domain: "larkspurconstruction.example.com",
    name: "Larkspur Construction Group",
    industry: "home_builder",
    state: "OH",
    city: "Westerville",
    revenueBand: "$7M–$11M",
    employeeBand: "30-45",
    status: "qualified",
    confidence: "verify",
    rejectionReason: null,
    founderName: "Anne Larkspur-Reed",
    founderTitle: "President",
    nextGenName: "Tyler Reed",
    nextGenTitle: "Site Supervisor",
    sourceUrl: "https://larkspurconstruction.example.com/about",
    firstSeenAt: "2026-07-31",
    lastCrawledAt: "2026-08-03",
    evidence: {
      quote:
        "\"Anne Larkspur-Reed leads our team. Tyler Reed supervises several of our active sites and has been with the company since 2019.\"",
      sourceUrl: "https://larkspurconstruction.example.com/about",
      pageType: "about",
      disproveNotes:
        "Shared surname suggests family tie but page never states the relationship explicitly, and no succession language appears. Flagged Verify — needs a human check on whether Tyler is actually Anne's son before this counts.",
    },
    contact: {
      name: "Tyler Reed",
      nameInferred: false,
      title: "Site Supervisor",
      email: "tyler@larkspurconstruction.example.com",
      findStatus: "found",
      verificationStatus: "unknown",
    },
  },
  {
    id: "co-008",
    domain: "bellmontlandscapegroup.example.com",
    name: "Bellmont Landscape Group",
    industry: "landscaping",
    state: "GA",
    city: "Marietta",
    revenueBand: "$5M–$8M",
    employeeBand: "25-40",
    status: "qualified",
    confidence: "high",
    rejectionReason: null,
    founderName: "Sam Bellmont",
    founderTitle: "Founder",
    nextGenName: "Nate Bellmont",
    nextGenTitle: "General Manager",
    sourceUrl: "https://bellmontlandscapegroup.example.com/our-story",
    firstSeenAt: "2026-07-22",
    lastCrawledAt: "2026-08-01",
    evidence: {
      quote:
        "\"Founded by Sam Bellmont in 1991. Sam is beginning to hand day-to-day leadership to his son Nate, our General Manager, as part of a planned multi-year transition.\"",
      sourceUrl: "https://bellmontlandscapegroup.example.com/our-story",
      pageType: "about",
      disproveNotes: "\"Planned multi-year transition\" is explicit and specific. Clean High.",
    },
    contact: {
      name: "Nate Bellmont",
      nameInferred: false,
      title: "General Manager",
      email: "nate@bellmontlandscapegroup.example.com",
      findStatus: "found",
      verificationStatus: "valid",
    },
  },
  {
    id: "co-009",
    domain: "kesslerandsons.example.com",
    name: "Kessler & Sons Building Co.",
    industry: "home_builder",
    state: "TX",
    city: "Pflugerville",
    revenueBand: "$4M–$7M",
    employeeBand: "18-30",
    status: "qualified",
    confidence: "medium",
    rejectionReason: null,
    founderName: "Don Kessler",
    founderTitle: "Owner",
    nextGenName: null,
    nextGenTitle: null,
    sourceUrl: "https://kesslerandsons.example.com/about",
    firstSeenAt: "2026-07-20",
    lastCrawledAt: "2026-08-01",
    evidence: {
      quote:
        "\"Kessler & Sons has built homes in the Austin area since 1976 — three generations of the Kessler family, still family-run today.\"",
      sourceUrl: "https://kesslerandsons.example.com/about",
      pageType: "about",
      disproveNotes:
        "Company name and copy strongly imply a next generation, but no individual next-gen name given on the page. Anymailfinder fallback used to find any owner/manager-role contact at the domain — see contact record (name inferred from email).",
    },
    contact: {
      name: "Mike",
      nameInferred: true,
      title: null,
      email: "mike@kesslerandsons.example.com",
      findStatus: "found",
      verificationStatus: "valid",
    },
  },
  {
    id: "co-010",
    domain: "cascadeoutdoorliving.example.com",
    name: "Cascade Outdoor Living",
    industry: "landscaping",
    state: "OH",
    city: "Powell",
    revenueBand: "$3M–$5M",
    employeeBand: "12-20",
    status: "rejected",
    confidence: null,
    rejectionReason: "Only the founder is listed — no next-gen name on the leadership page",
    founderName: "Linda Voss",
    founderTitle: "Owner",
    nextGenName: null,
    nextGenTitle: null,
    sourceUrl: "https://cascadeoutdoorliving.example.com/about",
    firstSeenAt: "2026-07-18",
    lastCrawledAt: "2026-08-04",
    evidence: {
      quote: "\"Linda Voss has run Cascade Outdoor Living single-handedly since 2005.\"",
      sourceUrl: "https://cascadeoutdoorliving.example.com/about",
      pageType: "about",
      disproveNotes: "No second generation named anywhere on the site. Rejected, not a Low confidence match.",
    },
    contact: null,
  },
  {
    id: "co-011",
    domain: "bramblewoodhomes.example.com",
    name: "Bramblewood Homes",
    industry: "home_builder",
    state: "NC",
    city: "Apex",
    revenueBand: "$8M–$12M",
    employeeBand: "35-50",
    status: "rejected",
    confidence: null,
    rejectionReason: "Professionally managed — no family-owned language or indicators",
    founderName: null,
    founderTitle: null,
    nextGenName: null,
    nextGenTitle: null,
    sourceUrl: "https://bramblewoodhomes.example.com/leadership",
    firstSeenAt: "2026-07-19",
    lastCrawledAt: "2026-08-02",
    evidence: {
      quote:
        "\"Bramblewood Homes is led by a management team of industry veterans with backgrounds at several regional builders.\"",
      sourceUrl: "https://bramblewoodhomes.example.com/leadership",
      pageType: "leadership",
      disproveNotes: "No family framing, no founder narrative — reads as professionally managed, not family-owned.",
    },
    contact: null,
  },
  {
    id: "co-012",
    domain: "harmonturftree.example.com",
    name: "Harmon Turf & Tree",
    industry: "landscaping",
    state: "GA",
    city: "Roswell",
    revenueBand: "$2M–$4M",
    employeeBand: "10-18",
    status: "rejected",
    confidence: null,
    rejectionReason: "Outside target revenue band",
    founderName: "Doug Harmon",
    founderTitle: "Owner",
    nextGenName: "Chris Harmon",
    nextGenTitle: "Crew Lead",
    sourceUrl: "https://harmonturftree.example.com/about",
    firstSeenAt: "2026-07-15",
    lastCrawledAt: "2026-08-01",
    evidence: {
      quote: "\"Doug and his son Chris run a tight, three-crew operation serving north Fulton County.\"",
      sourceUrl: "https://harmonturftree.example.com/about",
      pageType: "about",
      disproveNotes: "Signal itself is real — rejected on revenue band ($2-4M, below the $3-15M ICP floor), not on signal quality.",
    },
    contact: null,
  },
  {
    id: "co-013",
    domain: "fieldingcustombuilders.example.com",
    name: "Fielding Custom Builders",
    industry: "home_builder",
    state: "TX",
    city: "Leander",
    revenueBand: "$6M–$9M",
    employeeBand: "28-40",
    status: "rejected",
    confidence: null,
    rejectionReason: "Next-gen name present, but no succession or transition language found",
    founderName: "Roy Fielding",
    founderTitle: "Founder",
    nextGenName: "Ben Fielding",
    nextGenTitle: "Estimator",
    sourceUrl: "https://fieldingcustombuilders.example.com/team",
    firstSeenAt: "2026-07-21",
    lastCrawledAt: "2026-08-03",
    evidence: {
      quote:
        "\"Our estimating team includes Ben Fielding, who joined in 2022 after several years in commercial construction.\"",
      sourceUrl: "https://fieldingcustombuilders.example.com/team",
      pageType: "team",
      disproveNotes:
        "Shared surname with founder Roy Fielding, but bio gives an outside-hire narrative (\"after several years in commercial construction\"), not a family/succession one. Treated as coincidental surname, not a signal — rejected rather than scored Low.",
    },
    contact: null,
  },
  {
    id: "co-014",
    domain: "pinecrestgrounds.example.com",
    name: "Pinecrest Grounds Co.",
    industry: "landscaping",
    state: "OH",
    city: "Hilliard",
    revenueBand: "$4M–$6M",
    employeeBand: "20-30",
    status: "rejected",
    confidence: null,
    rejectionReason: "No About / Team / Leadership page found on the site",
    founderName: null,
    founderTitle: null,
    nextGenName: null,
    nextGenTitle: null,
    sourceUrl: "https://pinecrestgrounds.example.com/",
    firstSeenAt: "2026-07-16",
    lastCrawledAt: "2026-08-02",
    evidence: {
      quote: "No leadership, team, or about page reachable — site is a single-page contact form.",
      sourceUrl: "https://pinecrestgrounds.example.com/",
      pageType: "other",
      disproveNotes: "Apify fetch confirmed only 1 crawlable page exists. Re-check scheduled next run in case the site is expanded.",
    },
    contact: null,
  },
  {
    id: "co-015",
    domain: "northgatehomebuilders.example.com",
    name: "Northgate Home Builders",
    industry: "home_builder",
    state: "GA",
    city: "Woodstock",
    revenueBand: "$11M–$15M",
    employeeBand: "50-70",
    status: "rejected",
    confidence: null,
    rejectionReason: "Professionally managed — no family-owned language or indicators",
    founderName: null,
    founderTitle: null,
    nextGenName: null,
    nextGenTitle: null,
    sourceUrl: "https://northgatehomebuilders.example.com/about",
    firstSeenAt: "2026-07-14",
    lastCrawledAt: "2026-07-30",
    evidence: {
      quote: "\"Northgate is backed by a regional investment group and led by a hired executive team.\"",
      sourceUrl: "https://northgatehomebuilders.example.com/about",
      pageType: "about",
      disproveNotes: "Explicitly investment-backed, not family-owned — clean reject.",
    },
    contact: null,
  },
  {
    id: "co-016",
    domain: "silvanolandscapegroup.example.com",
    name: "Silvano Landscape Group",
    industry: "landscaping",
    state: "NC",
    city: "Wake Forest",
    revenueBand: "$5M–$7M",
    employeeBand: "22-35",
    status: "rejected",
    confidence: null,
    rejectionReason: "Duplicate of an already-tracked company",
    founderName: "Tony Silvano",
    founderTitle: "Owner",
    nextGenName: null,
    nextGenTitle: null,
    sourceUrl: "https://silvanolandscapegroup.example.com/about",
    firstSeenAt: "2026-07-13",
    lastCrawledAt: "2026-07-29",
    evidence: {
      quote: "Same entity as \"Silvano Grounds & Design\" (silvanogroundsdesign.example.com) — merged, single record kept.",
      sourceUrl: "https://silvanolandscapegroup.example.com/about",
      pageType: "other",
    },
    contact: null,
  },
  {
    id: "co-017",
    domain: "vandermeerconstruction.example.com",
    name: "Vandermeer Construction",
    industry: "home_builder",
    state: "OH",
    city: "Delaware",
    revenueBand: "$3M–$5M",
    employeeBand: "14-22",
    status: "rejected",
    confidence: null,
    rejectionReason: "Outside agreed states",
    founderName: "Erik Vandermeer",
    founderTitle: "Owner",
    nextGenName: "Josh Vandermeer",
    nextGenTitle: "Project Coordinator",
    sourceUrl: "https://vandermeerconstruction.example.com/about",
    firstSeenAt: "2026-07-12",
    lastCrawledAt: "2026-07-28",
    evidence: {
      quote: "\"Erik and Josh Vandermeer serve the greater Toledo area\" — outside the four agreed states' active regions for this build.",
      sourceUrl: "https://vandermeerconstruction.example.com/about",
      pageType: "about",
      disproveNotes: "Signal is real; geography is out of the agreed crawl scope for now. Kept, labeled, not deleted, in case scope expands.",
    },
    contact: null,
  },
  {
    id: "co-018",
    domain: "ridgelinelawncare.example.com",
    name: "Ridgeline Lawn Care",
    industry: "landscaping",
    state: "TX",
    city: "Cedar Park",
    revenueBand: "$3M–$4M",
    employeeBand: "16-24",
    status: "pending",
    confidence: null,
    rejectionReason: null,
    founderName: null,
    founderTitle: null,
    nextGenName: null,
    nextGenTitle: null,
    sourceUrl: "https://ridgelinelawncare.example.com/about",
    firstSeenAt: "2026-08-04",
    lastCrawledAt: "2026-08-04",
    evidence: null,
    contact: null,
  },
  {
    id: "co-019",
    domain: "marshfamilylandscaping.example.com",
    name: "Marsh Family Landscaping",
    industry: "landscaping",
    state: "GA",
    city: "Cumming",
    revenueBand: "$4M–$6M",
    employeeBand: "20-28",
    status: "pending",
    confidence: null,
    rejectionReason: null,
    founderName: null,
    founderTitle: null,
    nextGenName: null,
    nextGenTitle: null,
    sourceUrl: "https://marshfamilylandscaping.example.com/about",
    firstSeenAt: "2026-08-04",
    lastCrawledAt: "2026-08-04",
    evidence: null,
    contact: null,
  },
  {
    id: "co-020",
    domain: "fowlerbuilders.example.com",
    name: "Fowler Family Builders",
    industry: "home_builder",
    state: "NC",
    city: "Holly Springs",
    revenueBand: "$5M–$8M",
    employeeBand: "24-36",
    status: "qualified",
    confidence: "high",
    rejectionReason: null,
    founderName: "Grant Fowler",
    founderTitle: "Founder & Owner",
    nextGenName: "Olivia Fowler",
    nextGenTitle: "Head of Design",
    sourceUrl: "https://fowlerbuilders.example.com/about",
    firstSeenAt: "2026-08-03",
    lastCrawledAt: "2026-08-04",
    evidence: {
      quote:
        "\"Grant Fowler built his first home in 1996. Today his daughter Olivia leads design, and together they're planning her transition into full ownership over the next five years.\"",
      sourceUrl: "https://fowlerbuilders.example.com/about",
      pageType: "about",
      disproveNotes: "Explicit ownership-transition timeline stated. Clean High.",
    },
    contact: {
      name: "Olivia Fowler",
      nameInferred: false,
      title: "Head of Design",
      email: "olivia@fowlerbuilders.example.com",
      findStatus: "found",
      verificationStatus: "valid",
    },
  },
];
